# These are supported funding model platforms

github: Ahmed1Dev
patreon: Ahmed1Dev
open_collective: Ahmed Adel
ko_fi: Ahmed Adel
tidelift: npm/express + EJS
community_bridge: MiniCord
liberapay: EJS
issuehunt: EJS
otechie: Ahmed1Dev
lfx_crowdfunding: MiniCord
custom: ['https://discord.gg/h22fM858mG']
